apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: portfolio
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
